spring:
  config:
    activate:
      on-profile: prod
  application:
    name: perguntinhas
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: ${DATABASE_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none