spring:
  config:
    activate:
      on-profile: dev
  application:
    name: perguntinhas
  datasource:
    url: jdbc:postgresql://localhost:5454/perguntinhas
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5454/perguntinhas
    user: postgres
    password: postgres
    locations: classpath:db/migration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  web:
    resources:
      static-locations: classpath:/static/